# config.toml

[mcmc_params]
num_iterations = 1000
# initial_theta overrides other parameters.
# if a parameter is set here, then it will
# be estimated by MCMC. The value set here
# will override the filter_params below.
inital_theta = {'dispersion' = 1}

[filter_params]
num_particles = 500
dt = 1.0
seed_size = 0.03
dispersion = 1
beta_prior = [0.10, 0.3]

[model_params]
gamma = {value = 0.06, is_fixed = true}
# gamma = {dist = "normal", loc = 0.06, scale = 0.005, is_fixed = false}
mu = {value = 0.004, is_fixed = true}
q = {value = 0.1, is_fixed = true}
eta = {value = 0.1, is_fixed = true}
std = {value = 10.0, is_fixed = true}
R = {value = 50.0, is_fixed = true}
hosp = {value = 10, is_fixed = true}
L = {value = 90, is_fixed = true}
D = {value = 10, is_fixed = true}
dW_volatility = {value = 0.01, is_fixed = true}

# Params for the beta OU process
beta_theta = {value = 0.5, is_fixed = true}
beta_mu = {value = 0.25, is_fixed = true}
beta_sigma = {value=0.01, is_fixed = true}

[logging]
level = "INFO"
